version: "3"
services:
    nginx:
        image: "yachujeng/docker-flask:latest"
        build:
            context: .
        ports:
            - "8000:80"
            - "5000:5000"
        entrypoint: ./bin/entrypoint.sh
